# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplejob',
            name='query',
            field=models.CharField(default="SELECT source_id, ra, dec, phot_g_mean_flux, phot_g_mean_mag, \n    DISTANCE(POINT('ICRS',ra,dec), POINT('ICRS',266.41683,-29.00781)) \n    AS dist FROM gaiadr1.gaia_source WHERE \n    1=CONTAINS(POINT('ICRS',ra,dec), CIRCLE('ICRS',266.41683,-29.00781, 0.08333333))", max_length=1000),
        ),
        migrations.AlterField(
            model_name='simplejob',
            name='resources_cpu_cores',
            field=models.IntegerField(default=1, help_text='Number of CPU cores to be allocated to the AviJob'),
        ),
        migrations.AlterField(
            model_name='simplejob',
            name='resources_ram_mb',
            field=models.IntegerField(default=2000, help_text='Amount of RAM (M) to be allocated for the AviJob'),
        ),
    ]
