# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_auto_20161215_2018'),
        ('avi', '0002_auto_20180118_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuclidJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(editable=False, max_length=50, null=True)),
                ('expected_runtime', models.IntegerField(default=0)),
                ('resources_ram_mb', models.IntegerField(default=2000, help_text='Amount of RAM (M) to be allocated for the AviJob')),
                ('resources_cpu_cores', models.IntegerField(default=1, help_text='Number of CPU cores to be allocated to the AviJob')),
                ('query', models.CharField(default="SELECT DISTANCE(POINT('ICRS', rightascension, declination), \n                              POINT('ICRS',16.41683,4.90781)) AS dist, \n                     * FROM sc3_mer_cat_10 \n              WHERE 1=CONTAINS(POINT('ICRS', rightascension, declination), \n                               CIRCLE('ICRS',16.41683,4.90781, 26)) \n              ORDER BY dist ASC", max_length=1000)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='euclidjob_model', to='pipeline.AviJobRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='simplejob',
            name='request',
        ),
        migrations.DeleteModel(
            name='SimpleJob',
        ),
    ]
