# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-22 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avi', '0006_auto_20180122_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euclidjob',
            name='query',
            field=models.CharField(default="SELECT objectid, rightascension, declination, flagh, flagj, flagvis, flagy, fluxhaper, fluxjaper, fluxvisaper, fluxyaper,\n                      DISTANCE(POINT('ICRS', rightascension, declination), \n                              POINT('ICRS',16.41683,4.90781)) AS dist\n                      FROM sc3_mer_cat_10 \n              WHERE 1=CONTAINS(POINT('ICRS', rightascension, declination), \n                               CIRCLE('ICRS',16.41683,4.90781, 26)) \n              ORDER BY dist ASC", max_length=1000),
        ),
    ]
